mkdir C:\spei
rem tworzenie c/spei
copy spyvirus.py C:\spei
copy eiffel.jpg C:\spei
copy image.png C:\spei
copy rtd.py C:\spei
copy rtd1.py C:\spei
copy spy.png C:\spei
copy spyvirus.py C:\spei
copy spyvirus2.py C:\spei
copy starter.cmd C:\spei
copy wall.py C:\spei
copy weird.py C:\spei
copy autostart-master.cmd C:\spei
copy spy.py C:\spei
copy image.py C:\spei
copy downloader.cmd C:\spei
copy dasdas.py C:\spei
copy window1.py C:\spei
copy eiffel.jpg C:\Users\Public\Pictures\